CREATE DATABASE aptech_PHP_23_03;
DROP DATABASE aptech_php_23_03;
CREATE TABLE aptech_PHP_23_03.hocSinh(
	id INT PRIMARY KEY AUTO_INCREMENT
);
ALTER TABLE aptech_PHP_23_03.hocSinh
ADD name VARCHAR(255);